
#pragma config(Motor,  motor1,          left,          tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor6,          right,         tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
#pragma config(Motor,  motor8,          frontButton,   tmotorNone, openLoop)
#pragma config(Motor,  motor10,         clawUp,        tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor11,         claw,          tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void goL90(){
turnLeft(.68 ,rotations,60);
}
void goR90(){
turnRight(.68 ,rotations,60);
}
//* goes forward a number of rotation and speed
void goforward(int rotation,int speed){
setMotorSpeed(left, speed);
setMotorSpeed(right, speed);
int rotationsPerSecond = speed / 60;
int time = rotation / rotationsPerSecond;
sleep(time * 1000);
}
//* takes cm and turns it to rotations
int ToRotation(int num, int speed){
int number = num + 3;
int wheel_length = 6;
int wheel_cer = (wheel_length * 3.14);
int rotation = (number / wheel_cer);
return rotation;
}

task main(){
goforward(ToRotation(70,60), 60);
goL90();
goforward(ToRotation(70,60), 60);
goL90();
goforward(ToRotation(70,60), 60);
goR90();
goforward(ToRotation(70,60), 60);
goR90();
goforward(ToRotation(70,60), 60);
goL90();
goforward(ToRotation(70,60), 60);

}
